### ISSUE TITLE
footer is floating

### ISSUE THREAD

**Issue by TomWoodward** [golavender/golavender.github.io#11]
http://screencast.com/t/hzqiHpnEmQ

**Comment by sugarPhlox** [comment]
Which browser? I cannot see the issue from Chrome or Safari, could be related to screen size?

**Comment by TomWoodward** [comment]
i suspect your browser just doesn't get tall enough for you to notice, try
removing all the content and you'll probably see the footer doesn't stay at
the bottom of the page
