### ISSUE TITLE
there should be a main call to action on the homepage

### ISSUE THREAD

**Issue by jtgraphic** [golavender/golavender.github.io#29]
"Download Now" that goes to a download page with installation instructions

on the download page, include:
- git
- download link
- composer

You can lift the installation instructions from the language reference page.

good example:

http://haml.info/ and
http://haml.info/download.html

**Comment by sugarPhlox** [comment]
@jtgraphic With the navbar now DRY, this 'Download' link is gone, so I don't know if this applies anymore. Should we still add one to the guide just incase?

**Comment by jtgraphic** [comment]
This still applies.

**Comment by avophile** [comment]
done
