### ISSUE TITLE
There should not be a space between the dash and the declaration of "some_array"s

### ISSUE THREAD

**Issue by avophile** [golavender/golavender.github.io#42]
In the variables section of the Lavender guide, there should not be a space between the dash and the declaration of "some_array"s. -some_array works in code as does - some_array.

**Comment by sugarPhlox** [comment]
Was this issue fixed?

**Comment by jtgraphic** [comment]
Can you link the line of code this happens on? I'm unclear still as to what the issue is.

**Comment by avophile** [comment]
@jtgraphic 

In array (and variable declarations) both methods work, whether you put a space between the dash and the space or not. Feature or bug? What will our standard be? The declarations in our documentation should adhere to the standard. 

![spaces or not in array declarations](https://cloud.githubusercontent.com/assets/11019935/6557441/5a23ddb6-c64b-11e4-8327-c28e5eb77faf.png)

![variable declarations with space after dash](https://cloud.githubusercontent.com/assets/11019935/6558017/cae30a5a-c64f-11e4-8fef-5d4a19458328.png)

**Comment by avophile** [comment]
Basically, we should have a standard as to whether or not there is a space between the dash and the variable name.

**Comment by sugarPhlox** [comment]
@jtgraphic , do we want -some_variable or - some_variable to be the standard?

**Comment by TomWoodward** [comment]
i tend to do `-variable = "foobar"` but its still valid with the extra space, expressions in general are not really whitespace sensitive
