### ISSUE TITLE
Links should be readable

### ISSUE THREAD

**Issue by avophile** [golavender/golavender.github.io#50]
The color should be changed on this link so that it is readable no matter what part of the background image it is scrolled over. 

![unreadable link](https://cloud.githubusercontent.com/assets/11019935/6557838/95616bca-c64e-11e4-903c-7196418514e6.png)

**Comment by sugarPhlox** [comment]
@mowchan , got any ideas for colors that will still match the theme of the website? Apparently my colors aren't holding up for this little bit of tree area.

**Comment by mowchan** [comment]
White? Black with underline?

**Comment by sugarPhlox** [comment]
I think black bold w/ underline may be the only option here. I mean, this works and looks nice except in that one spot.
