### ISSUE TITLE
The keys filter should be explained more clearly.

### ISSUE THREAD

**Issue by avophile** [golavender/golavender.github.io#54]
I am not sure if the values are missing here or if this is how keys are supposed to work.

![are keys missing here](https://cloud.githubusercontent.com/assets/11019935/6558712/332903a4-c654-11e4-97a0-1c4b1cc05b03.png)

**Comment by sugarPhlox** [comment]
The line break makes this one a little weird in your current browser size and it does need a little clarification, but this is correct.

{'asdf': 'foo','qwer': 'bar'}|keys -- > ['asdf', 'qwer']

so, 'asdf':'foo' becomes the array 'asdf', and 'qwer':'bar' becomes the array 'qwer'.
