### ISSUE TITLE
The text for the relative helper is cut off.

### ISSUE THREAD

**Issue by avophile** [golavender/golavender.github.io#60]
The text for the relative helper is cut off.

![relative helper cut off](https://cloud.githubusercontent.com/assets/11019935/6560384/040485b0-c660-11e4-953e-2971801a1dd4.png)

**Comment by sugarPhlox** [comment]
This table is responsive, meaning is scrolls side to side when browser size is too small.

**Comment by avophile** [comment]
The issue appears no matter what size browser I use I believe.

![join and last cut off](https://cloud.githubusercontent.com/assets/11019935/6560451/79b99e12-c660-11e4-9bc1-c7f4a5626af6.png)

![number format cut off](https://cloud.githubusercontent.com/assets/11019935/6560449/75dc6978-c660-11e4-84c8-b7f515df7c83.png)

**Comment by sugarPhlox** [comment]
http://screencast.com/t/WQaskHk8

This is so code does not get broken up and becomes hard to understand.

**Comment by avophile** [comment]
Ohhhh. I missed the scroll bar. Thanks for teaching me internets!

**Comment by sugarPhlox** [comment]
The scroll bar is stupidly hard to find on Mac's OSX, so no worries! It's just easier to find with a Magic Mouse, trackpad, or a phone's touch screen. Since Bootstrap was built mobile first, a lot of their stuff is super mobile friendly.

**Comment by avophile** [comment]
When responsive pages are scrolling, lines break on whole words, which is good. However, code chunks are broken any which way, leading to code to be split in the middle. Is it possible to have code chunks maintain their integrity? I will investigate.

**Comment by avophile** [comment]
Never mind. This way is the best way.
