### ISSUE TITLE
Stop stacking of footer when in mobile.

### ISSUE THREAD

**Issue by sugarPhlox** [golavender/golavender.github.io#66]
http://screencast.com/t/xf89Zs8hT - Yes
http://screencast.com/t/YRk7aRB0B - No. Bad footer, bad.
Starts at 992px.

Fix can be done after #64 Pull Request is accepted.

**Comment by avophile** [comment]
I also noticed there seems to be very little padding between the bottom of the logo in the footer and the bottom of my browser window.
