### ISSUE TITLE
"=" symbol should be rendered with a standard of no space

### ISSUE THREAD

**Issue by avophile** [golavender/golavender.github.io#75]

**Comment by sugarPhlox** [comment]
Where is this being shown?

**Comment by avophile** [comment]
@sugarPhlox 

![equals sign spacing](https://cloud.githubusercontent.com/assets/11019935/6692263/1a54e682-cca2-11e4-9580-f4411335be03.png)

Sometimes:
 span.foo = some_variable

Others: 

span.foo= some_variable

Sometimes the use of whitespace and the "=" operator is syntactically significant (see #51).
