### ISSUE TITLE
Lavender Guide nav still wonky.

### ISSUE THREAD

**Issue by sugarPhlox** [golavender/golavender.github.io#86]
http://screencast.com/t/htOikzi1YVgg
1. Scroll to bottom. Nav bar floats fine.
2. Get close to bottom. Nav suddenly slightly changes size.
3. Hit bottom. Nav disappears.
4. Scroll to the top of the page, there's the nav!
5. Scroll down, the nav will not float after this.

**Comment by sugarPhlox** [comment]
@mowchan , why is the nav so cranky. plz help stops. thanks.

**Comment by sugarPhlox** [comment]
New wonk:

http://screencast.com/t/5gft4vHYiUw

**Comment by avophile** [comment]
@sugarPhlox We fixed this, yes?

**Comment by sugarPhlox** [comment]
Yeah, it's totally on my home laptop however.
